# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RACDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  # Pods for RACDemo

pod 'ReactiveCocoa', '~> 4.0.2-alpha-1'

  target 'RACDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RACDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
